import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/Nav/Nav";
import { Inter as FontSans } from "next/font/google"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
import { cn } from "@/lib/utils"





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={cn(
          "min-h-screen bg-background font-sans antialiased bg-gray-800 text-white text-xl overflow-hidden h-full leading-tight",
          fontSans.variable
        )}>
        <Nav/>
        {children}
        </body>
      
    </html>
  );
}
